In [6]:
import numpy as np
import pandas as pd

Loading the data set downloaded from Kaggle : https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset/data

In [10]:
data = pd.read_csv('spam.csv')
data.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

Data Preprocessing :

In [11]:
print(data)

        v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN
1      ham                      Ok lar... Joking wif u oni...        NaN
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN
3      ham  U dun say so early hor... U c already then say...        NaN
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN
...    ...                                                ...        ...
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN
5568   ham              Will Ì_ b going to esplanade fr home?        NaN
5569   ham  Pity, * was in mood for that. So...any other s...        NaN
5570   ham  The guy did some bitching but I acted like i'd...        NaN
5571   ham                         Rofl. Its true to its name        NaN

     Unnamed: 3 Unnamed: 4
0           NaN        NaN
1           NaN        NaN
2           NaN        NaN
3           NaN        NaN
4           NaN        NaN
...         ...        ...
5567        NaN        NaN
5568        NaN        NaN
5569        NaN        NaN
5570        NaN        NaN
5571        NaN        NaN

[5572 rows x 5 columns]

In [12]:
# replace the null values with a null string
data = data.where((pd.notnull(data)),'')

# removing empty columns
data = data.iloc[:, :2]

In [13]:
# printing the first 5 rows of the dataframe
data.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

V1 - Classification
V2 - Message

In [14]:
# checking the number of rows and columns in the dataframe
data.shape

(5572, 2)

In [15]:
# label spam mail as 0;  ham mail as 1;
data.loc[data['v1'] == 'spam', 'v1',] = 0
data.loc[data['v1'] == 'ham', 'v1',] = 1

In [16]:
# separating the data as texts (inputs) and label(target)
X = data['v2']
Y = data['v1']

In [17]:
print(X)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: v2, Length: 5572, dtype: object

In [18]:
print(Y)

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: v1, Length: 5572, dtype: object

Splitting the data set into Training data and Testing data

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

Creating a TfidfVectorizer object :
It is a numerical statistic that reflects how important a word is to a document in a collection or corpus. It's a product of two metrics: Term Frequency (TF) and Inverse Document Frequency (IDF).

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

# transform the text data to feature vectors that can be used as input to the Logistic regression
feature_extraction = TfidfVectorizer(min_df = 1, stop_words='english', lowercase=True)

X_train_features = feature_extraction.fit_transform(X_train)
X_test_features = feature_extraction.transform(X_test)

# convert Y_train and Y_test values as integers
Y_train = Y_train.astype('int')
Y_test = Y_test.astype('int')

In [21]:
print(X_train)

1978    No I'm in the same boat. Still here at my moms...
3989    (Bank of Granite issues Strong-Buy) EXPLOSIVE ...
3935       They r giving a second chance to rahul dengra.
4078       O i played smash bros  &lt;#&gt;  religiously.
4086    PRIVATE! Your 2003 Account Statement for 07973...
                              ...
3772    I came hostel. I m going to sleep. Plz call me...
5191                               Sorry, I'll call later
5226        Prabha..i'm soryda..realy..frm heart i'm sory
5390                           Nt joking seriously i told
860                   In work now. Going have in few min.
Name: v2, Length: 4457, dtype: object

In [22]:
print(X_train_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34794 stored elements and shape (4457, 7472)>
  Coords	Values
  (0, 1371)	0.4658046386365619
  (0, 4416)	0.4528381701109944
  (0, 1706)	0.3431839629173582
  (0, 7415)	0.348722265231364
  (0, 3210)	0.348722265231364
  (0, 4520)	0.4658046386365619
  (1, 1187)	0.26161139982801973
  (1, 3140)	0.3059746053542906
  (1, 3631)	0.2804339696184593
  (1, 6296)	0.269833648032668
  (1, 1533)	0.2015782058421696
  (1, 2661)	0.3059746053542906
  (1, 5005)	0.1937920260229529
  (1, 4292)	0.2953742837684993
  (1, 419)	0.28715203556385105
  (1, 4533)	0.3059746053542906
  (1, 6440)	0.2953742837684993
  (1, 1649)	0.3059746053542906
  (1, 0)	0.2654936554684193
  (2, 3061)	0.44585171875646595
  (2, 5770)	0.3962151014046925
  (2, 1674)	0.35156722029872034
  (2, 5351)	0.5102109014477275
  (2, 2190)	0.5102109014477275
  (3, 5048)	0.4444794309161828
  :	:
  (4451, 5002)	0.36484607066812064
  (4451, 4939)	0.36484607066812064
  (4452, 3085)	0.25923599228241945
  (4452, 5070)	0.3823754823843719
  (4452, 5998)	0.3311324953642251
  (4452, 1781)	0.3311324953642251
  (4452, 1579)	0.3576443319642905
  (4452, 3423)	0.4833413012939851
  (4452, 3402)	0.4536077050510107
  (4453, 4022)	0.5251399912435084
  (4453, 3896)	0.6138307933697734
  (4453, 6102)	0.5894401977366341
  (4454, 3282)	0.31753127203477105
  (4454, 5161)	0.43497582872738466
  (4454, 6109)	0.44743083090000146
  (4454, 5413)	0.40874206042479744
  (4454, 2938)	0.3775064911532845
  (4454, 6108)	0.44743083090000146
  (4455, 3720)	0.5663548747533713
  (4455, 4674)	0.47741741602516974
  (4455, 5819)	0.5321975225970689
  (4455, 6701)	0.40997629646174116
  (4456, 3085)	0.5132022683472269
  (4456, 7301)	0.5938942231507836
  (4456, 4332)	0.6196072009518515

Importing the Dependencies of the Required ML Models to Experiment on the given data set:

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [24]:
model_lr = LogisticRegression() #Logistic Regression Classification Model

# training the Logistic Regression model with the training data
model_lr.fit(X_train_features, Y_train)

# prediction on training data
prediction_on_training_data = model_lr.predict(X_train_features)
accuracy_on_training_data = accuracy_score(Y_train, prediction_on_training_data)
print('Accuracy on training data : ', accuracy_on_training_data)

# prediction on test data
prediction_on_test_data = model_lr.predict(X_test_features)
accuracy_on_test_data = accuracy_score(Y_test, prediction_on_test_data)
print('Accuracy on test data : ', accuracy_on_test_data)

Accuracy on training data :  0.9692618353152345
Accuracy on test data :  0.9524663677130045

In [25]:
model_nb = MultinomialNB() # Naive Bayes Classification Model

# training the Logistic Regression model with the training data
model_nb.fit(X_train_features, Y_train)

# prediction on training data
prediction_on_training_data = model_nb.predict(X_train_features)
accuracy_on_training_data = accuracy_score(Y_train, prediction_on_training_data)
print('Accuracy on training data : ', accuracy_on_training_data)

# prediction on test data
prediction_on_test_data = model_nb.predict(X_test_features)
accuracy_on_test_data = accuracy_score(Y_test, prediction_on_test_data)
print('Accuracy on test data : ', accuracy_on_test_data)

Accuracy on training data :  0.9838456360780794
Accuracy on test data :  0.9668161434977578

In [26]:
model_svc = SVC(kernel='linear') # Support Vector Classification Model

# training the Logistic Regression model with the training data
model_svc.fit(X_train_features, Y_train)

# prediction on training data
prediction_on_training_data = model_svc.predict(X_train_features)
accuracy_on_training_data = accuracy_score(Y_train, prediction_on_training_data)
print('Accuracy on training data : ', accuracy_on_training_data)

# prediction on test data
prediction_on_test_data = model_svc.predict(X_test_features)
accuracy_on_test_data = accuracy_score(Y_test, prediction_on_test_data)
print('Accuracy on test data : ', accuracy_on_test_data)

Accuracy on training data :  0.9973076060130133
Accuracy on test data :  0.979372197309417

Thus, Support Vector Classifier has the best accuracy score over training data of 99.73%

Testing the Model :

In [27]:
input_mail = ["Winner!!You won the million dollar lottery, call this Nuber 56783894 and share your bank data to win the price 450000"]

# convert text to feature vectors
input_data_features = feature_extraction.transform(input_mail)

# making prediction using SVC Model
prediction = model_svc.predict(input_data_features)
print(prediction)

if (prediction[0]==1):
  print('Legitimate SMS')
else:
  print('Spam SMS')

[0]
Spam SMS